version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
