[setup]
apt_pkgs = ["chromium-browser"]

[build]
cmd = "npm install && npm run build"

[start]
cmd = "npm run start"

[environment]
NODE_ENV = "production"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
