[setup]
apt_pkgs = ["chromium", "chromium-l10n", "libx11-xcb1", "libxcomposite1", "libxcursor1", "libxdamage1", "libxi6", "libxtst6", "libnss3", "libcups2", "libxss1", "libxrandr2", "libasound2", "libatk1.0-0", "libatk-bridge2.0-0", "libpangocairo-1.0-0", "libgtk-3-0", "libgbm1"]

[build]
cmds = [
  "apt-get update",
  "apt-get install -y chromium",
  "which chromium",
  "npm install",
  "npm run build"
]

[start]
cmd = "npm run start"

[environment]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
